CREATE TABLE IF NOT EXISTS states (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  overall_risk TEXT NOT NULL DEFAULT 'Moderate',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cities (
  id SERIAL PRIMARY KEY,
  state_id TEXT NOT NULL REFERENCES states(id) ON DELETE CASCADE,
  city_name TEXT NOT NULL,
  district TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  source TEXT NOT NULL,
  tds INTEGER NOT NULL,
  ph DOUBLE PRECISION NOT NULL,
  turbidity DOUBLE PRECISION NOT NULL,
  fluoride DOUBLE PRECISION NOT NULL,
  nitrate INTEGER NOT NULL,
  arsenic DOUBLE PRECISION NOT NULL,
  risk TEXT NOT NULL,
  reason TEXT NOT NULL,
  contaminants TEXT[] NOT NULL DEFAULT '{}',
  updated_at TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS water_quality_readings (
  id SERIAL PRIMARY KEY,
  state_id TEXT NOT NULL REFERENCES states(id) ON DELETE CASCADE,
  city_name TEXT NOT NULL,
  district TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  source TEXT NOT NULL,
  tds INTEGER NOT NULL,
  ph DOUBLE PRECISION NOT NULL,
  turbidity DOUBLE PRECISION NOT NULL,
  fluoride DOUBLE PRECISION NOT NULL,
  nitrate INTEGER NOT NULL,
  arsenic DOUBLE PRECISION NOT NULL,
  risk TEXT NOT NULL,
  reason TEXT NOT NULL,
  contaminants TEXT[] NOT NULL DEFAULT '{}',
  updated_at TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS risk_snapshots (
  id SERIAL PRIMARY KEY,
  state_id TEXT NOT NULL REFERENCES states(id) ON DELETE CASCADE,
  overall_risk TEXT NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER states_updated_at
BEFORE UPDATE ON states
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
